from .rankcard import rankcard
from .trigger import trigger
from .communism import communism
from .gay import gay
from .jail import jail
from .hitler import hitler
from .spank import spank
from .aborted import aborted
from .affect import affect
from .airpods import airpods
from .america import america
from .bed import bed
from .wanted import wanted
from .jokeoverhead import jokeoverhead
from .versionchecker import checkversion
from .avatar import avatar